"""
MuleTrace AI — Alert Model.

Represents suspicious activity alerts generated by the Rule Engine, ML Engine, or Graph Engine.
"""

import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base, TimestampMixin


class Alert(Base, TimestampMixin):
    """Alert entity.

    Generated when an account or transaction exceeds risk thresholds or matches
    known fraud patterns.
    """

    __tablename__ = "alerts"
    __table_args__ = (
        CheckConstraint("risk_score >= 0 AND risk_score <= 100", name="check_alert_risk_score_range"),
    )

    alert_number: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        nullable=False,
        index=True,
        comment="Unique alert reference (e.g. ALT-2025-00123)",
    )
    title: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        comment="Alert summary title",
    )
    pattern_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
        comment="Fraud pattern name (Mule Chain, Fan In, Smurfing, etc.)",
    )
    severity: Mapped[str] = mapped_column(
        String(20),
        default="MEDIUM",
        nullable=False,
        index=True,
        comment="Alert severity (LOW, MEDIUM, HIGH, CRITICAL)",
    )
    risk_score: Mapped[int] = mapped_column(
        Integer,
        default=50,
        nullable=False,
        index=True,
        comment="Alert risk score (0-100)",
    )
    alert_status: Mapped[str] = mapped_column(
        String(30),
        default="NEW",
        nullable=False,
        index=True,
        comment="Triage status (NEW, UNDER_INVESTIGATION, ESCALATED, CLOSED_FALSE_POSITIVE, CLOSED_CONFIRMED)",
    )
    triggered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
        comment="Alert generation timestamp",
    )
    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Detailed description / explanation narrative",
    )

    # ── Foreign Keys ──────────────────────────────────────────────────
    account_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("accounts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Flagged account ID",
    )
    case_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("cases.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Associated investigation case ID (if assigned)",
    )

    # ── Relationships ──────────────────────────────────────────────────
    account: Mapped["Account"] = relationship(  # noqa: F821
        "Account",
        back_populates="alerts",
    )
    case: Mapped["Case | None"] = relationship(  # noqa: F821
        "Case",
        back_populates="alerts",
    )

    def __repr__(self) -> str:
        return f"<Alert(number={self.alert_number}, pattern={self.pattern_type}, severity={self.severity})>"
