"""Initial schema setup

Revision ID: 6622db121ee1
Revises: 
Create Date: 2026-07-24 21:43:08.949867
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# Revision identifiers, used by Alembic.
revision: str = '6622db121ee1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration — forward."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atms',
    sa.Column('terminal_id', sa.String(length=50), nullable=False, comment='Unique ATM Terminal ID'),
    sa.Column('bank_name', sa.String(length=200), nullable=False, comment='Bank managing this ATM'),
    sa.Column('location_name', sa.String(length=250), nullable=False, comment='ATM location display name'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='City'),
    sa.Column('state', sa.String(length=100), nullable=False, comment='State'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='Latitude'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='Longitude'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='Record status (active, inactive, deleted, flagged, frozen, under_review)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atms_bank_name'), 'atms', ['bank_name'], unique=False)
    op.create_index(op.f('ix_atms_city'), 'atms', ['city'], unique=False)
    op.create_index(op.f('ix_atms_created_at'), 'atms', ['created_at'], unique=False)
    op.create_index(op.f('ix_atms_id'), 'atms', ['id'], unique=False)
    op.create_index(op.f('ix_atms_status'), 'atms', ['status'], unique=False)
    op.create_index(op.f('ix_atms_terminal_id'), 'atms', ['terminal_id'], unique=True)
    op.create_table('branches',
    sa.Column('branch_code', sa.String(length=20), nullable=False, comment='Unique branch code'),
    sa.Column('branch_name', sa.String(length=200), nullable=False, comment='Branch display name'),
    sa.Column('bank_name', sa.String(length=200), nullable=False, comment='Parent bank name'),
    sa.Column('ifsc_code', sa.String(length=11), nullable=False, comment='IFSC code (11 characters)'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='City where branch is located'),
    sa.Column('state', sa.String(length=100), nullable=False, comment='State where branch is located'),
    sa.Column('address', sa.Text(), nullable=True, comment='Full branch address'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='Branch latitude for geo intelligence'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='Branch longitude for geo intelligence'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='Record status (active, inactive, deleted, flagged, frozen, under_review)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_bank_name'), 'branches', ['bank_name'], unique=False)
    op.create_index(op.f('ix_branches_branch_code'), 'branches', ['branch_code'], unique=True)
    op.create_index(op.f('ix_branches_city'), 'branches', ['city'], unique=False)
    op.create_index(op.f('ix_branches_created_at'), 'branches', ['created_at'], unique=False)
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_index(op.f('ix_branches_ifsc_code'), 'branches', ['ifsc_code'], unique=True)
    op.create_index(op.f('ix_branches_state'), 'branches', ['state'], unique=False)
    op.create_index(op.f('ix_branches_status'), 'branches', ['status'], unique=False)
    op.create_table('cases',
    sa.Column('case_number', sa.String(length=50), nullable=False, comment='Unique case reference (e.g. CAS-2025-0045)'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Case subject / title'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='Case priority (LOW, MEDIUM, HIGH, CRITICAL)'),
    sa.Column('case_status', sa.String(length=30), nullable=False, comment='Case status (OPEN, IN_PROGRESS, PENDING_REVIEW, CLOSED_CONFIRMED, CLOSED_FALSE_POSITIVE)'),
    sa.Column('assigned_investigator_id', sa.String(length=100), nullable=True, comment='ID of the assigned analyst/investigator'),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False, comment='Case creation timestamp'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='Case closure timestamp'),
    sa.Column('summary_notes', sa.Text(), nullable=True, comment='Investigator findings & summary notes'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='Record status (active, inactive, deleted, flagged, frozen, under_review)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_assigned_investigator_id'), 'cases', ['assigned_investigator_id'], unique=False)
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_case_status'), 'cases', ['case_status'], unique=False)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_index(op.f('ix_cases_priority'), 'cases', ['priority'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('rules',
    sa.Column('rule_code', sa.String(length=20), nullable=False, comment='Unique rule code (e.g. R001, R002)'),
    sa.Column('rule_name', sa.String(length=150), nullable=False, comment='Human-readable rule name'),
    sa.Column('pattern_name', sa.String(length=50), nullable=False, comment='Associated pattern (High Velocity, Fan In, Circular Loop, etc.)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Rule rationale and detection criteria'),
    sa.Column('risk_score_contribution', sa.Integer(), nullable=False, comment='Points added to risk score upon rule match'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Toggle state for rule evaluation'),
    sa.Column('threshold_value', sa.Float(), nullable=True, comment='Numeric threshold for rule trigger'),
    sa.Column('time_window_minutes', sa.Integer(), nullable=True, comment='Time window window in minutes for velocity evaluation'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='Record status (active, inactive, deleted, flagged, frozen, under_review)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_created_at'), 'rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_index(op.f('ix_rules_is_active'), 'rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_rules_pattern_name'), 'rules', ['pattern_name'], unique=False)
    op.create_index(op.f('ix_rules_rule_code'), 'rules', ['rule_code'], unique=True)
    op.create_index(op.f('ix_rules_status'), 'rules', ['status'], unique=False)
    op.create_table('accounts',
    sa.Column('account_number', sa.String(length=34), nullable=False, comment='Account number (IBAN / Account No)'),
    sa.Column('customer_id', sa.String(length=50), nullable=False, comment='Associated customer/CIF ID'),
    sa.Column('customer_name', sa.String(length=200), nullable=False, comment='Account holder full name'),
    sa.Column('account_type', sa.String(length=50), nullable=False, comment='Account type (savings, current, salary, wallet)'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency code (ISO 4217)'),
    sa.Column('balance', sa.Float(), nullable=False, comment='Current ledger balance'),
    sa.Column('risk_score', sa.Integer(), nullable=False, comment='Dynamic risk score (0-100)'),
    sa.Column('risk_level', sa.String(length=20), nullable=False, comment='Risk level (LOW, MEDIUM, HIGH, CRITICAL)'),
    sa.Column('is_flagged_mule', sa.Boolean(), nullable=False, comment='Flagged as confirmed or suspected mule account'),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True, comment='Account opening timestamp'),
    sa.Column('branch_id', sa.UUID(), nullable=True, comment='Home branch ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='Record status (active, inactive, deleted, flagged, frozen, under_review)'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='check_risk_score_range'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_accounts_branch_id'), 'accounts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_is_flagged_mule'), 'accounts', ['is_flagged_mule'], unique=False)
    op.create_index(op.f('ix_accounts_risk_level'), 'accounts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_accounts_risk_score'), 'accounts', ['risk_score'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('report_number', sa.String(length=50), nullable=False, comment='Unique report reference (e.g. STR-2025-0089)'),
    sa.Column('report_type', sa.String(length=30), nullable=False, comment='Report type (STR, CTR, CYBERCRIME_SUMMARY, EXECUTIVE_BRIEF)'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Report document title'),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False, comment='Generation timestamp'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='Stored PDF/JSON report artifact path or URL'),
    sa.Column('summary_text', sa.Text(), nullable=True, comment='LLM-generated executive narrative'),
    sa.Column('case_id', sa.UUID(), nullable=True, comment='Associated case ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='Record status (active, inactive, deleted, flagged, frozen, under_review)'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_number'), 'reports', ['report_number'], unique=True)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_number', sa.String(length=50), nullable=False, comment='Unique alert reference (e.g. ALT-2025-00123)'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Alert summary title'),
    sa.Column('pattern_type', sa.String(length=50), nullable=False, comment='Fraud pattern name (Mule Chain, Fan In, Smurfing, etc.)'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='Alert severity (LOW, MEDIUM, HIGH, CRITICAL)'),
    sa.Column('risk_score', sa.Integer(), nullable=False, comment='Alert risk score (0-100)'),
    sa.Column('alert_status', sa.String(length=30), nullable=False, comment='Triage status (NEW, UNDER_INVESTIGATION, ESCALATED, CLOSED_FALSE_POSITIVE, CLOSED_CONFIRMED)'),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False, comment='Alert generation timestamp'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description / explanation narrative'),
    sa.Column('account_id', sa.UUID(), nullable=False, comment='Flagged account ID'),
    sa.Column('case_id', sa.UUID(), nullable=True, comment='Associated investigation case ID (if assigned)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='Record status (active, inactive, deleted, flagged, frozen, under_review)'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='check_alert_risk_score_range'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_account_id'), 'alerts', ['account_id'], unique=False)
    op.create_index(op.f('ix_alerts_alert_number'), 'alerts', ['alert_number'], unique=True)
    op.create_index(op.f('ix_alerts_alert_status'), 'alerts', ['alert_status'], unique=False)
    op.create_index(op.f('ix_alerts_case_id'), 'alerts', ['case_id'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_pattern_type'), 'alerts', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_alerts_risk_score'), 'alerts', ['risk_score'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_table('beneficiaries',
    sa.Column('beneficiary_account_number', sa.String(length=34), nullable=False, comment='Beneficiary account number'),
    sa.Column('beneficiary_name', sa.String(length=200), nullable=False, comment='Beneficiary name'),
    sa.Column('bank_name', sa.String(length=200), nullable=True, comment='Target bank name'),
    sa.Column('ifsc_code', sa.String(length=11), nullable=True, comment='IFSC code'),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when beneficiary was registered'),
    sa.Column('account_id', sa.UUID(), nullable=False, comment='Account that added this beneficiary'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='Record status (active, inactive, deleted, flagged, frozen, under_review)'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiaries_account_id'), 'beneficiaries', ['account_id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_beneficiary_account_number'), 'beneficiaries', ['beneficiary_account_number'], unique=False)
    op.create_index(op.f('ix_beneficiaries_created_at'), 'beneficiaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_beneficiaries_id'), 'beneficiaries', ['id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_ifsc_code'), 'beneficiaries', ['ifsc_code'], unique=False)
    op.create_index(op.f('ix_beneficiaries_status'), 'beneficiaries', ['status'], unique=False)
    op.create_table('devices',
    sa.Column('device_fingerprint', sa.String(length=100), nullable=False, comment='Unique hardware/browser fingerprint'),
    sa.Column('device_model', sa.String(length=100), nullable=True, comment='Device brand/model (e.g. Samsung Galaxy S23)'),
    sa.Column('os_version', sa.String(length=50), nullable=True, comment='Operating system & version'),
    sa.Column('app_version', sa.String(length=50), nullable=True, comment='Banking app version'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='Last active timestamp for this device'),
    sa.Column('shared_account_count', sa.Integer(), nullable=False, comment='Number of distinct accounts linked to this device'),
    sa.Column('account_id', sa.UUID(), nullable=False, comment='Associated account ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='Record status (active, inactive, deleted, flagged, frozen, under_review)'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_account_id'), 'devices', ['account_id'], unique=False)
    op.create_index(op.f('ix_devices_created_at'), 'devices', ['created_at'], unique=False)
    op.create_index(op.f('ix_devices_device_fingerprint'), 'devices', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_table('ip_addresses',
    sa.Column('ip_str', sa.String(length=45), nullable=False, comment='IPv4 or IPv6 address string'),
    sa.Column('isp', sa.String(length=150), nullable=True, comment='Internet Service Provider'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='Geo city'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='Geo country'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='Geo latitude'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='Geo longitude'),
    sa.Column('is_vpn_or_proxy', sa.Boolean(), nullable=False, comment='Indicates whether IP is a known VPN, proxy, or TOR exit node'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last active timestamp for this IP'),
    sa.Column('associated_accounts_count', sa.Integer(), nullable=False, comment='Count of distinct accounts accessing from this IP'),
    sa.Column('account_id', sa.UUID(), nullable=False, comment='Associated account ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='Record status (active, inactive, deleted, flagged, frozen, under_review)'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_addresses_account_id'), 'ip_addresses', ['account_id'], unique=False)
    op.create_index(op.f('ix_ip_addresses_city'), 'ip_addresses', ['city'], unique=False)
    op.create_index(op.f('ix_ip_addresses_created_at'), 'ip_addresses', ['created_at'], unique=False)
    op.create_index(op.f('ix_ip_addresses_id'), 'ip_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_ip_addresses_ip_str'), 'ip_addresses', ['ip_str'], unique=False)
    op.create_index(op.f('ix_ip_addresses_status'), 'ip_addresses', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_ref', sa.String(length=100), nullable=False, comment='Unique transaction reference number (e.g., UTR / RRN)'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='Payment channel (UPI, NEFT, IMPS, RTGS)'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Transaction amount in local currency'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency code'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Transaction execution timestamp'),
    sa.Column('location_city', sa.String(length=100), nullable=True, comment='Transaction origination city'),
    sa.Column('location_state', sa.String(length=100), nullable=True, comment='Transaction origination state'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='Geo latitude'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='Geo longitude'),
    sa.Column('ip_address_str', sa.String(length=45), nullable=True, comment='IP address string at time of transaction'),
    sa.Column('device_fingerprint', sa.String(length=100), nullable=True, comment='Device hardware/browser fingerprint'),
    sa.Column('risk_score', sa.Integer(), nullable=False, comment='Transaction-level risk score (0-100)'),
    sa.Column('flagged_pattern', sa.String(length=100), nullable=True, comment='Detected pattern name (e.g. Mule Chain, Fan In)'),
    sa.Column('narrative', sa.Text(), nullable=True, comment='Transaction description or remarks'),
    sa.Column('sender_account_id', sa.UUID(), nullable=False, comment='Sender account ID'),
    sa.Column('receiver_account_id', sa.UUID(), nullable=False, comment='Receiver account ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='Record status (active, inactive, deleted, flagged, frozen, under_review)'),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_amount'), 'transactions', ['amount'], unique=False)
    op.create_index(op.f('ix_transactions_channel'), 'transactions', ['channel'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_device_fingerprint'), 'transactions', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_transactions_flagged_pattern'), 'transactions', ['flagged_pattern'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_ip_address_str'), 'transactions', ['ip_address_str'], unique=False)
    op.create_index(op.f('ix_transactions_location_city'), 'transactions', ['location_city'], unique=False)
    op.create_index(op.f('ix_transactions_receiver_account_id'), 'transactions', ['receiver_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_risk_score'), 'transactions', ['risk_score'], unique=False)
    op.create_index(op.f('ix_transactions_sender_account_id'), 'transactions', ['sender_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_ref'), 'transactions', ['transaction_ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration — rollback."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_ref'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_sender_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_risk_score'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_receiver_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_location_city'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ip_address_str'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_flagged_pattern'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_device_fingerprint'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_channel'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_amount'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_ip_addresses_status'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_ip_str'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_id'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_created_at'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_city'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_account_id'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_fingerprint'), table_name='devices')
    op.drop_index(op.f('ix_devices_created_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_account_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_beneficiaries_status'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_ifsc_code'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_created_at'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_beneficiary_account_number'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_account_id'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_risk_score'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_pattern_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_case_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_number'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_account_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_number'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_risk_score'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_risk_level'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_flagged_mule'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_branch_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_rules_status'), table_name='rules')
    op.drop_index(op.f('ix_rules_rule_code'), table_name='rules')
    op.drop_index(op.f('ix_rules_pattern_name'), table_name='rules')
    op.drop_index(op.f('ix_rules_is_active'), table_name='rules')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_created_at'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_priority'), table_name='cases')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_investigator_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_branches_status'), table_name='branches')
    op.drop_index(op.f('ix_branches_state'), table_name='branches')
    op.drop_index(op.f('ix_branches_ifsc_code'), table_name='branches')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_created_at'), table_name='branches')
    op.drop_index(op.f('ix_branches_city'), table_name='branches')
    op.drop_index(op.f('ix_branches_branch_code'), table_name='branches')
    op.drop_index(op.f('ix_branches_bank_name'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_atms_terminal_id'), table_name='atms')
    op.drop_index(op.f('ix_atms_status'), table_name='atms')
    op.drop_index(op.f('ix_atms_id'), table_name='atms')
    op.drop_index(op.f('ix_atms_created_at'), table_name='atms')
    op.drop_index(op.f('ix_atms_city'), table_name='atms')
    op.drop_index(op.f('ix_atms_bank_name'), table_name='atms')
    op.drop_table('atms')
    # ### end Alembic commands ###
